version: '2.4'
services:
    php5.5-fpm:
        hostname: php5.5-fpm
        build: php-fpm/
        container_name: php5.5-fpm
        expose:
          - "9000"
        depends_on: 
          - mysql5.6
        volumes:
            - .:/var/www/html/openbiblio
        environment: 
          - OBIB_HOST=mysql5.6
          - OBIB_DATABASE=openbiblio
          - OBIB_USERNAME=openbiblio
          - OBIB_PWD=openbiblio
          - TIMEZONE=America/Sao_Paulo
      
    mysql5.6:
        container_name: mysql5.6
        hostname: mysql5.6
        image: mysql:5.6
        volumes:
          - mysql-data:/var/lib/mysql
        environment: 
          - MYSQL_DATABASE=openbiblio
          - MYSQL_USER=openbiblio
          - MYSQL_PASSWORD=openbiblio
          - MYSQL_ROOT_PASSWORD=root
        ports:
          - 3307:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        hostname: phpmyadmin
        depends_on: 
          - mysql5.6
        ports:
          - 82:80
        environment: 
          - MYSQL_USER=openbiblio
          - MYSQL_PASSWORD=openbiblio
          - MYSQL_ROOT_PASSWORD=root
    nginx:
      image: nginx:latest
      container_name: nginx
      hostname: nginx
      volumes:
            - .:/var/www/html/openbiblio
            - ./nginx/openbiblio.dev.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 81:80
      depends_on: 
        - php5.5-fpm
      
volumes:
  mysql-data:
